language: php
sudo: false

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

addons:
  #firefox: "47.0.1"
  postgresql: "9.6"
  #apt:
  #  packages:
  #    - oracle-java8-installer
  #    - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
  - MOODLE_BRANCH=master DB=pgsql
  - MOODLE_BRANCH=master DB=mysqli

matrix:
  exclude:
  # Do not test with PHP 5.6 on post-33 branches
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
  - php: 5.6
    env: MOODLE_BRANCH=master DB=mysqli
  - php: 5.6
    env: MOODLE_BRANCH=master DB=pgsql
  # Do not test with PHP 7.0 on pre-34 and master branches
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
  - php: 7.0
    env: MOODLE_BRANCH=master DB=mysqli
  - php: 7.0
    env: MOODLE_BRANCH=master DB=pgsql
  - php: 7.0
  # Do not test with PHP 7.1 on pre-34 and master branches
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
  - php: 7.1
    env: MOODLE_BRANCH=master DB=mysqli
  - php: 7.1
    env: MOODLE_BRANCH=master DB=pgsql
  # Do not test with PHP 7.2 on pre-34 branches
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9.0
  - nvm use 8.9.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

jobs:
  include:
    # Prechecks against one configuration (Moodle, PHP, DB) only.
    - stage: prechecks
      php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
      install:
      - moodle-plugin-ci install --no-init
      script:
      - moodle-plugin-ci phplint
      #- moodle-plugin-ci phpcpd #disable cpd for now - reports duplicates as failures - would be nice to fix.
      - moodle-plugin-ci phpmd
      - moodle-plugin-ci codechecker
      - moodle-plugin-ci validate
      - moodle-plugin-ci savepoints
      - moodle-plugin-ci mustache
      # - moodle-plugin-ci grunt

# Unit tests and behat tests against full matrix (Implicit "test" stage).
install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat
#  - vendor/bin/phpunit --coverage-clover=coverage.xml

stages:
  - prechecks
  - test

# after_success:
#  - bash <(curl -s https://codecov.io/bash)
